#!/bin/bash

# Generated by Gemini
# What it does: It gets all the links (https://) that were ever put in README.md to reflect how many articles I have read since the beggining of the research.
git log --format=%H -- README.md | xargs -I {} git show {}:README.md | grep -oE 'https://[^ ">)]+' | sort -u >article_links.txt

# Future task: instead of getting links, get the patterns that match "[](https://)" to get the title of the articles + links
